config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords'
  }

  namespace :admins do
    resources :dashboard
  end

  namespace :front do
    resources :home
  end

  root to: 'customers/students#index'

  namespace :customers do
    resources :courses do
      collection do
        get :get_teachers
        get :load_table_data
      end
    end
    resources :teachers
    resources :dashboard
    resources :birthdays
    resources :students do
      member do
        get 'media'
        put 'restore'
      end
      collection do
        get 'reload_student_table'
        put 'swap_positions'
        get 'reload_current_page'
      end
    end
    resources :customers

    # resources :medias
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/teacher.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: teachers
#
#  id         :bigint           not null, primary key
#  age        :integer
#  deleted_at :datetime
#  name       :string(255)
#  position   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  school_id  :bigint
#
# Indexes
#
#  index_teachers_on_deleted_at  (deleted_at)
#  index_teachers_on_school_id   (school_id)
#
# Foreign Keys
#
#  fk_rails_...  (school_id => schools.id)
#
class Teacher < ApplicationRecord
  before_create :set_default_position
  has_many :courses, class_name: 'course', foreign_key: 'reference_id'
  belongs_to :school

  validates :school_id, :name, :age, presence: true

  paginates_per 10

  acts_as_paranoid

  def self.ransackable_attributes(_auth_object = nil)
    %w[age created_at deleted_at id name position school_id updated_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[courses school]
  end

  def set_default_position
    highest_position = Teacher.maximum(:position)
    self.position = highest_position ? highest_position + 1 : 1
  end
end

app/controllers/customers/teachers_controller.rb
# frozen_string_literal: true

module Customers
  class TeachersController < Customers::CustomersController
    before_action :set_teacher, only: %i[show edit update destroy]

    # GET /teachers or /teachers.json
    def index
      @teachers = params[:deleted] == 'true' ? Teacher.only_deleted.includes(:school) : Teacher.includes(:school)
      @q = @teachers.ransack(params[:q])
      @teachers = @q.result.order(position: :desc, id: :desc).page(params[:page])
    end

    # GET /teachers/1 or /teachers/1.json
    def show; end

    # GET /teachers/new
    def new
      @teacher = Teacher.new
    end

    # GET /teachers/1/edit
    def edit
      respond_to do |format|
        format.html
        format.turbo_stream
      end
    end

    # POST /teachers or /teachers.json
    def create
      @teacher = Teacher.new(teacher_params)

      respond_to do |format|
        if @teacher.save
          format.html { redirect_to customers_teachers_url, notice: 'Teacher was successfully created.' }
          format.turbo_stream
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /teachers/1 or /teachers/1.json
    def update
      respond_to do |format|
        if @teacher.update(teacher_params)
          format.html { redirect_to customers_teacher_url(@teacher), notice: 'Teacher was successfully updated.' }
          format.json { render :show, status: :ok, location: @teacher }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @teacher.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /teachers/1 or /teachers/1.json
    def destroy
      @teacher.destroy

      respond_to do |format|
        format.html { redirect_to customers_teacher_url, notice: 'Teacher was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teacher_params
      params.require(:teacher).permit(:name, :age, :school_id)
    end
  end
end

app/helpers/teachers_helper.rb
# frozen_string_literal: true

module TeachersHelper
end

app/views/customers/teachers/partial/_form.html.erb
<%= form_with( model: [:customers,teacher], local: false) do |form| %>

  <div class="row">
    <div class="col">
      <%= form.label :name, "Name" %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
    <div class="col">
      <%= form.label :age, "Age" %>
      <%= form.number_field :age, class: 'form-control' %>
    </div>
    <div class="col">
      <%= form.label :school_id, "School" %>
      <%= form.select :school_id, ["Select school"] + School.all.map{|s| [s.name, s.id] }, {}, class:"form-control" %>
    </div>
  </div>
  <div class="form-actions">
    <%= form.submit "Submit", class: "btn btn-success mt-2" %>
  </div>
<% end %>

app/views/customers/teachers/partial/_table.html.erb
<table class="table mx-auto table-striped table-bordered table-condensed text-center align-middle">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Age</th>
      <th scope="col">School</th>
      <th scope="col">Position</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody id="teachers">
    <% teachers.each do |teacher| %>
      <%= render "customers/teachers/partial/teacher" , teacher: teacher %>
    <% end %>
  </tbody>
</table>
<div class="d-flex justify-content-end" id="paginate-element">
  <%= paginate teachers, theme: 'bootstrap-5',
        params: {controller: 'teachers', action: 'index'} %></div>

app/views/customers/teachers/partial/_teacher.html.erb
<tr>
  <td><%= teacher.id %></td>
  <td><%= teacher.name %></td>
  <td><%= teacher.age %></td>
  <td><%= teacher.school.name %></td>
  <td><%= teacher.position %></td>
  <td>
    <%= link_to "Edit", edit_customers_teacher_path(teacher),data: { turbo_frame: "teacher-update" },  class: "btn btn-primary" %>
    <button class="btn btn-danger delete_teacher" data-teacher-id="<%= teacher.id %>" >Delete</button>
  </td>
</tr>